# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
  pt_BR: Miguel Alfredo Nunes
  en: Miguel Alfredo Nunes
  de: Miguel Alfredo Nunes
email: miguel.alfredo.nunes@gmail.com
description:
  pt_BR: Aluno de Doutorado em Filosofia na UNICAMP, lógico e cientista da computação. #Nesse blog escrevei e divagarei sobre estes e outros assuntos.
  en: PhD student of Philosophy at UNICAMP, logician and computer scientist. #In this blog I'll write and digress about these and other topics.
  de: Doktorand der Philosophie an der UNICAMP, Logiker und Informatiker. Ich spreche noch kein Deutsch, daher werden die Updates auf Deutsch langsam sein. #In diesem Blog schreibe und schweife ich über diese und andere themen ab.
date_formats:
  pt_BR: "%Y-%m-%d"
  en: "%Y-%m-%d"
  de: "%Y-%m-%d"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miguelanunes.github.io/"
github_username: MiguelANunes

# Build settings
remote_theme: MiguelANunes/migs-hydeout
plugins:
  - jekyll-feed


# Configurações para múltiplos idiomas
languages: ["pt_BR", "en", "de"]
default_lang: "pt_BR"
exclude_from_localization: ["assets", "javascript", "images", "css", "public"]
parallel_localization: true

include:
  - _pages

# Configurando renderizador de markdown como o kramdown para a tag <details> do HTML ser renderizada direito
# markdown: kramdown
# kramdown:
#   parse_block_html: true